# feeder
feeder: feeders.feeder.ChaLearnFeeder
train_feeder_args:
  data_path: /vol/research/SignTranslation/data/ChaLearn2021/train/ChaLearn2021.train.holistic.fp16_eps.slt.full
  label_path: ./data/ntu/xview/val_label.pkl
  window_size: 157
  random_choose: False
  debug: False
  type: holistic
#  random_move: True

test_feeder_args:
  data_path: /vol/research/SignTranslation/data/ChaLearn2021/val/ChaLearn2021.val.holistic.fp16_eps.slt
  label_path: ./data/ntu/xview/val_label.pkl
  window_size: 157
  random_choose: False
  debug: False
  type: holistic

# model
model: model.msg3d.Model
model_args:
  num_class: 226
  num_point: 30  #30 for fingers (5*2*2), 8 for none
  num_person: 1
  num_gcn_scales: 8    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 8
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: train
device: [0]
test_batch_size: 1

assume_yes: True

save_score: True
num_epoch: 160

# Training args
# The models were trained with SGD with Nes- terov’s accelerated gradient
# (momentum: 0.9, batch size: 64, weight decay: 0.0003, initial learning rate: 0.1)
# with a step LR decay factor of 0.1 at epochs 45 and 55
optimizer: SGD
nesterov: True
batch_size: 1 #64
weight_decay: 0.0003
base_lr: 0.1
step: [45, 55]
forward_batch_size: 1 #16
