# feeder
feeder: feeders.feeder.PhoenixFeeder
train_feeder_args:
  data_path: [/vol/research/extol/data/Phoenix2014T/Holistic/train/16_zero.slt, /vol/research/extol/data/Phoenix2014T/Holistic/dev/16_zero.slt]
  label_path: ./data/ntu/xview/val_label.pkl
  window_size: 16
  random_choose: False
  debug: False
  type: holistic
  start: 600
#  random_move: True

test_feeder_args:
  data_path: /vol/research/extol/data/Phoenix2014T/Holistic/train/16_zero.slt
  end: 600
  label_path: ./data/ntu/xview/val_label.pkl
  window_size: 16
  random_choose: False
  debug: False
  type: holistic
print_log: False
# model
model: model.msg3d.Model
model_args:
  num_class: 1201
  num_point: 30  #30 for fingers (5*2*2), 8 for none
  num_person: 1
  num_gcn_scales: 8    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 8
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: train
device: [0]
test_batch_size: 512

assume_yes: True

save_score: True
num_epoch: 160

# Training args
# The models were trained with SGD with Nes- terov’s accelerated gradient
# (momentum: 0.9, batch size: 64, weight decay: 0.0003, initial learning rate: 0.1)
# with a step LR decay factor of 0.1 at epochs 45 and 55
optimizer: SGD
nesterov: True
batch_size: 512 #64
weight_decay: 0.0003
base_lr: 0.1
step: [20, 30 40]
forward_batch_size: 512 #16
